jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: ./mvnw clean package
      - name: Build Docker image
        run: |
          docker build -t backend .
          docker tag backend kscofre/backend:latest
          docker push kscofre/backend:latest