name: Deploy to VMSS (Azure)
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
jobs:
  DEPLOY-TO-TEST:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Azure CLI
        uses: elstudio/action-install-azure-cli@v1
        with:
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Deploy to Test
        run: |
          az login --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}
          az vmss extension set --name CustomScript --publisher Microsoft.Azure.Extensions --version 2.1 --resource-group DevOpsGroup --vmss-name DevOpsScaling --settings '{"commandToExecute": "sh /home/azureuser/backend/update.sh"}'